version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only: 
    - master
only_commits:
  files:
  - StringAsSql/*
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
before_build:
  - cmd: nuget restore
configuration: ReleaseCI